import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { Activity, Bell, BrainCircuit, CheckCircle2, ChevronRight, Cpu, FileText, Fingerprint, Globe2, KeyRound, LayoutDashboard, Lock, LogOut, Network, Radar, RadioTower, Search, Server, Settings, Shield, ShieldAlert, Siren, Skull, Timer, UserCheck, Users, Zap } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

const WS = import.meta.env.VITE_WS_URL || 'ws://localhost:8000/ws/alerts';
const severityColors = { Critical: '#fb3457', High: '#ff9f1c', Medium: '#2fd6ff', Low: '#39ff88' };
const demoUser = { name: 'Sahil Khan', email: 'admin@neuroshield.ai', role: 'Admin' };
const navItems = [['Dashboard','/dashboard',LayoutDashboard], ['Alerts','/alerts',ShieldAlert], ['Incidents','/incidents',Siren], ['Threat Intel','/threat-intel',Globe2], ['MITRE','/mitre',Radar], ['Endpoints','/endpoints',Server], ['Reports','/reports',FileText], ['Admin','/admin',Users], ['Settings','/settings',Settings], ['Profile','/profile',Fingerprint]];
const alertsSeed = [
  { id:'ALT-9001', title:'Credential stuffing against VPN gateway', severity:'Critical', status:'Open', source_ip:'185.199.108.44', endpoint:'vpn-edge-01', technique:'T1110', risk:96, confidence:94, explanation:'High failed-login velocity, external ASN risk, and repeated username spray pattern.' },
  { id:'ALT-9002', title:'Suspicious PowerShell encoded command', severity:'High', status:'Investigating', source_ip:'10.8.4.23', endpoint:'win-fin-014', technique:'T1059.001', risk:84, confidence:89, explanation:'Encoded shell execution with child process behavior matching malware staging.' },
  { id:'ALT-9003', title:'Unusual login time for privileged user', severity:'Medium', status:'Open', source_ip:'45.83.64.12', endpoint:'idp-core', technique:'T1078', risk:68, confidence:81, explanation:'Login occurred outside baseline window from untrusted geography.' },
  { id:'ALT-9004', title:'Malware hash detected on endpoint', severity:'Critical', status:'Contained', source_ip:'10.8.9.71', endpoint:'eng-ws-228', technique:'T1204', risk:92, confidence:91, explanation:'File hash matches known loader family and endpoint activity is abnormal.' }
];
const incidentsSeed = [{ id:'INC-2410', title:'VPN brute force campaign', severity:'Critical', status:'Active', analyst:'Ayesha Malik', assets:['vpn-edge-01','idp-core'], timeline:['Alert correlated','Credential access mapped','Temporary blocklist applied'], remediation:'Enforce MFA reset, block source ranges, rotate affected accounts.' }, { id:'INC-2411', title:'Finance workstation malware execution', severity:'High', status:'Investigating', analyst:'Sahil Khan', assets:['win-fin-014'], timeline:['Endpoint isolated','Memory triage queued'], remediation:'Isolate host, remove persistence, verify backups.' }];
const endpointsSeed = [{ host:'vpn-edge-01', os:'Ubuntu 22.04', status:'Online', health:'Degraded', risk:91, last:'2 min ago' },{ host:'win-fin-014', os:'Windows 11', status:'Online', health:'Critical', risk:87, last:'1 min ago' },{ host:'eng-ws-228', os:'Windows 10', status:'Isolated', health:'At Risk', risk:78, last:'8 min ago' },{ host:'mac-exec-07', os:'macOS 15', status:'Online', health:'Healthy', risk:22, last:'4 min ago' }];
const iocsSeed = [{ type:'IP', value:'185.199.108.44', status:'Malicious', confidence:96, linked:'INC-2410' },{ type:'Hash', value:'b1946ac92492d2347c6235b4d2611184', status:'Malware', confidence:92, linked:'INC-2411' },{ type:'Domain', value:'updatecdn-security.net', status:'Suspicious', confidence:74, linked:'INC-2411' }];
const mitreSeed = [{ behavior:'Brute Force', tactic:'Credential Access', technique:'T1110', detections:42 },{ behavior:'Valid Accounts', tactic:'Defense Evasion', technique:'T1078', detections:18 },{ behavior:'PowerShell', tactic:'Execution', technique:'T1059.001', detections:25 },{ behavior:'User Execution', tactic:'Execution', technique:'T1204', detections:11 }];
const trend = [{n:'Mon',alerts:42,critical:7},{n:'Tue',alerts:55,critical:10},{n:'Wed',alerts:61,critical:12},{n:'Thu',alerts:48,critical:8},{n:'Fri',alerts:79,critical:16},{n:'Sat',alerts:38,critical:5},{n:'Sun',alerts:44,critical:6}];
const killChain = [{label:'Recon', value:72}, {label:'Initial Access', value:91}, {label:'Execution', value:63}, {label:'Persistence', value:41}, {label:'Exfiltration', value:18}];
const socQueue = [{label:'MTTA', value:'4m', icon:Timer}, {label:'Blocked IOCs', value:'186', icon:Lock}, {label:'Analysts Online', value:'7', icon:UserCheck}, {label:'AI Confidence', value:'94%', icon:BrainCircuit}];
function useAuth(){ const [user,setUser] = useState(()=>JSON.parse(localStorage.getItem('ns-user')||'null')); const login = (email)=>{ const role = email.includes('viewer')?'Viewer':email.includes('analyst')?'Analyst':'Admin'; const next={...demoUser,email,role,name: role==='Admin'?'Sahil Khan':role+' User'}; localStorage.setItem('ns-user',JSON.stringify(next)); localStorage.setItem('ns-token','demo-jwt-token'); setUser(next); }; const logout = ()=>{ localStorage.removeItem('ns-user'); localStorage.removeItem('ns-token'); setUser(null); }; return { user, login, logout }; }
function Shell({auth,children}){ const location=useLocation(); return <div className="app-shell"><CyberBg/><aside className="sidebar"><div className="brand"><Shield className="brand-icon"/><div><b>NeuroShield</b><span>AI SOC/XDR</span></div></div><nav>{navItems.map(([label,to,Icon])=><a key={to} className={location.pathname.startsWith(to)?'active':''} href={to}><Icon size={18}/><span>{label}</span></a>)}</nav></aside><main className="main"><Topbar auth={auth}/><AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-14}} transition={{duration:.22}}>{children}</motion.div></AnimatePresence></main></div> }
function Topbar({auth}){ return <header className="topbar"><div><p>AI-Powered Security Operations</p><h1>Threat Monitoring Command Center</h1></div><div className="top-actions"><button className="icon-btn"><Search size={18}/></button><button className="icon-btn glow"><Bell size={18}/></button><a className="profile-mini" href="/profile"><span>{auth.user?.role||'Guest'}</span><b>{auth.user?.name||'Operator'}</b></a><button onClick={auth.logout} className="icon-btn"><LogOut size={18}/></button></div></header> }
function CyberBg(){ return <div className="cyber-bg"><span/><span/><span/></div> }
function Stat({icon:Icon,label,value,tone='cyan'}){ return <motion.div whileHover={{y:-4,scale:1.01}} className={'glass stat '+tone}><Icon/><p>{label}</p><strong>{value}</strong></motion.div> }
function Dashboard(){ const [feed,setFeed]=useState(alertsSeed); useEffect(()=>{ let socket; try{ socket=new WebSocket(WS); socket.onmessage=e=>setFeed(x=>[JSON.parse(e.data),...x].slice(0,6)); }catch{} const id=setInterval(()=>setFeed(x=>[{...alertsSeed[Math.floor(Math.random()*alertsSeed.length)],id:'ALT-'+Math.floor(1000+Math.random()*9000)},...x].slice(0,6)),5000); return()=>{clearInterval(id); socket?.close?.();}; },[]); return <Page title="Dashboard" kicker="Live security posture"><section className="command-hero glass"><div><span className="live-pill"><RadioTower size={14}/> Live XDR telemetry</span><h2>Neural threat operations center</h2><p>Real-time alert correlation, endpoint risk scoring, AI severity prediction, and MITRE ATT&CK mapping across the enterprise estate.</p><div className="hero-actions"><a className="primary" href="/alerts">Triage Alerts</a><a className="ghost-btn" href="/reports">Generate Report</a></div></div><ThreatMap/></section><div className="stats-grid"><Stat icon={ShieldAlert} label="Total Alerts" value="1,284"/><Stat icon={Skull} label="Critical Alerts" value="37" tone="red"/><Stat icon={Server} label="Endpoints" value="428"/><Stat icon={Siren} label="Open Incidents" value="12" tone="amber"/><Stat icon={Lock} label="Blocked IPs" value="186"/><Stat icon={Zap} label="Suspicious Logins" value="74" tone="red"/></div><div className="queue-grid">{socQueue.map(({label,value,icon:Icon})=><motion.div className="queue-card glass" whileHover={{y:-3}} key={label}><Icon size={18}/><span>{label}</span><b>{value}</b></motion.div>)}</div><div className="grid two"><Panel title="Alert Velocity"><ResponsiveContainer height={280}><AreaChart data={trend}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2fd6ff" stopOpacity=".8"/><stop offset="1" stopColor="#2fd6ff" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="n"/><YAxis/><Tooltip/><Area dataKey="alerts" stroke="#2fd6ff" fill="url(#g)"/><Area dataKey="critical" stroke="#fb3457" fill="#fb345733"/></AreaChart></ResponsiveContainer></Panel><Panel title="Live Alert Feed"><div className="feed">{feed.map(a=><motion.a href={'/alerts/'+a.id} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} className={'feed-item '+(a.severity==='Critical'?'critical-pulse':'')} key={a.id+a.title}><span style={{background:severityColors[a.severity]}}/><div><b>{a.title}</b><small>{a.id} | {a.endpoint} | {a.technique}</small></div><strong>{a.severity}</strong></motion.a>)}</div></Panel></div><div className="grid three"><Panel title="MITRE Kill Chain Pressure"><KillChain/></Panel><Panel title="Endpoint Risk Fabric"><RiskFabric/></Panel><Panel title="AI Decision Layer"><AiLayer/></Panel></div></Page> }
function ThreatMap(){ return <div className="threat-map"><Network className="map-icon"/>{['na','eu','ap','core','edge'].map((n,i)=><motion.span key={n} className={'node '+n} animate={{scale:[1,1.25,1], opacity:[.65,1,.65]}} transition={{duration:2.2+i*.2, repeat:Infinity}}/>)}<i/><em/></div> }
function KillChain(){ return <div className="kill-chain">{killChain.map(k=><div className="kill-row" key={k.label}><div><span>{k.label}</span><b>{k.value}%</b></div><div className="meter"><i style={{width:k.value+'%'}}/></div></div>)}</div> }
function RiskFabric(){ return <div className="risk-fabric">{endpointsSeed.map(e=><div className="risk-row" key={e.host}><Cpu size={16}/><div><b>{e.host}</b><span>{e.os}</span></div><strong>{e.risk}</strong></div>)}</div> }
function AiLayer(){ return <div className="ai-layer"><BrainCircuit/><h4>Severity model active</h4><p>Random Forest scoring + Isolation Forest anomaly hints are attached to alert triage and incident reports.</p><div className="chips"><span>Risk scoring</span><span>Anomaly flags</span><span>Explainable AI</span></div></div> }
function Alerts(){ const [q,setQ]=useState(''); const filtered=alertsSeed.filter(a=>(a.title+a.source_ip+a.severity+a.status).toLowerCase().includes(q.toLowerCase())); return <Page title="Alerts" kicker="Search, filter, triage"><Toolbar q={q} setQ={setQ}/><div className="table glass">{filtered.map(a=><a href={'/alerts/'+a.id} className="row" key={a.id}><span className="sev" style={{color:severityColors[a.severity]}}>{a.severity}</span><b>{a.title}</b><span>{a.source_ip}</span><span>{a.status}</span><ChevronRight size={18}/></a>)}</div></Page> }
function AlertDetails(){ const {id}=useParams(); const a=alertsSeed.find(x=>x.id===id)||alertsSeed[0]; return <Page title={a.id} kicker={a.title}><div className="grid two"><Panel title="AI Severity Prediction"><div className="score">{a.risk}<span>risk</span></div><p>{a.explanation}</p><div className="chips"><span>{a.severity}</span><span>{a.confidence}% confidence</span><span>{a.technique}</span></div></Panel><Panel title="Detection Context"><Info label="Source IP" value={a.source_ip}/><Info label="Endpoint" value={a.endpoint}/><Info label="Status" value={a.status}/><Info label="MITRE Technique" value={a.technique}/></Panel></div></Page> }
function Incidents(){ return <Page title="Incidents" kicker="Case management"><div className="cards">{incidentsSeed.map(i=><a className="glass card" href={'/incidents/'+i.id} key={i.id}><h3>{i.title}</h3><p>{i.id} | {i.analyst}</p><div className="chips"><span>{i.severity}</span><span>{i.status}</span><span>{i.assets.length} assets</span></div></a>)}</div></Page> }
function IncidentDetails(){ const {id}=useParams(); const i=incidentsSeed.find(x=>x.id===id)||incidentsSeed[0]; return <Page title={i.id} kicker={i.title}><div className="grid two"><Panel title="Incident Timeline">{i.timeline.map((t,n)=><div className="timeline" key={t}><span>{n+1}</span><b>{t}</b></div>)}</Panel><Panel title="AI Incident Report"><p><b>Summary:</b> {i.title} is linked to {i.assets.join(', ')} with {i.severity.toLowerCase()} business risk.</p><p><b>Root Cause:</b> Exposed authentication surface and abnormal endpoint execution patterns.</p><p><b>Remediation:</b> {i.remediation}</p><button className="primary">Export Markdown/PDF</button></Panel></div></Page> }
function ThreatIntel(){ return <Page title="Threat Intelligence" kicker="IOC reputation and linking"><div className="table glass">{iocsSeed.map(i=><div className="row" key={i.value}><span>{i.type}</span><b>{i.value}</b><span>{i.status}</span><span>{i.confidence}%</span><span>{i.linked}</span></div>)}</div></Page> }
function Mitre(){ return <Page title="MITRE Mapping" kicker="ATT&CK tactics and techniques"><div className="grid two"><Panel title="Technique Distribution"><ResponsiveContainer height={260}><BarChart data={mitreSeed}><XAxis dataKey="technique"/><YAxis/><Tooltip/><Bar dataKey="detections" fill="#2fd6ff"/></BarChart></ResponsiveContainer></Panel><Panel title="Mapped Behaviors">{mitreSeed.map(m=><Info key={m.technique} label={m.behavior} value={m.tactic+' -> '+m.technique}/>)}</Panel></div></Page> }
function Endpoints(){ return <Page title="Endpoints" kicker="Agent health and endpoint risk"><div className="cards">{endpointsSeed.map(e=><div className="glass card" key={e.host}><h3>{e.host}</h3><p>{e.os} | {e.last}</p><div className="meter"><i style={{width:e.risk+'%'}}/></div><div className="chips"><span>{e.status}</span><span>{e.health}</span><span>{e.risk} risk</span></div></div>)}</div></Page> }
function Reports(){ return <Page title="Reports" kicker="AI-generated incident documentation"><Panel title="Generated Reports"><p>Reports include executive summary, root cause, evidence logs, MITRE mapping, timeline, remediation, and conclusion.</p><button className="primary">Generate Incident Report</button></Panel></Page> }
function Admin(){ return <Page title="Admin Dashboard" kicker="Users, roles, audit, rules"><div className="stats-grid"><Stat icon={Users} label="Users" value="18"/><Stat icon={Activity} label="Audit Events" value="2,904"/><Stat icon={Bell} label="Rules" value="64"/><Stat icon={CheckCircle2} label="Notifications" value="Enabled"/></div></Page> }
function SimplePage({title,kicker}){ return <Page title={title} kicker={kicker}><Panel title={title+' Controls'}><p>Enterprise-ready controls, preferences, audit visibility, and notification placeholders are available for this module.</p></Panel></Page> }
function Login({auth,mode='login'}){ const nav=useNavigate(); const submit=e=>{e.preventDefault(); auth.login(e.currentTarget.email.value); nav('/dashboard');}; return <div className="auth-screen"><CyberBg/><motion.form initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} onSubmit={submit} className="auth-card glass"><Shield className="brand-icon"/><h1>{mode==='register'?'Create NeuroShield Account':'NeuroShield AI'}</h1><p>AI-powered SOC/XDR threat monitoring platform</p><input name="email" defaultValue="admin@neuroshield.ai"/><input name="password" type="password" defaultValue="NeuroShield@123"/><button className="primary">{mode==='register'?'Register':'Login'}</button><a href={mode==='register'?'/login':'/register'}>{mode==='register'?'Already have an account?':'Need an account?'}</a></motion.form></div> }
function Landing(){ return <div className="landing"><CyberBg/><section><Shield className="brand-icon"/><h1>NeuroShield AI</h1><p>AI-powered SOC/XDR threat monitoring with real-time alerts, MITRE ATT&CK mapping, incident response, and executive-grade reporting.</p><a className="primary" href="/login">Open Command Center</a></section></div> }
function Page({title,kicker,children}){ return <section className="page"><div className="page-head"><p>{kicker}</p><h2>{title}</h2></div>{children}</section> }
function Panel({title,children}){ return <motion.div whileHover={{borderColor:'rgba(47,214,255,.38)'}} className="glass panel"><h3>{title}</h3>{children}</motion.div> }
function Toolbar({q,setQ}){ return <div className="toolbar glass"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search severity, status, source IP, endpoint..."/><select><option>All severities</option><option>Critical</option><option>High</option></select><select><option>All statuses</option><option>Open</option><option>Contained</option></select></div> }
function Info({label,value}){ return <div className="info"><span>{label}</span><b>{value}</b></div> }
function Protected({auth,children}){ return auth.user ? <Shell auth={auth}>{children}</Shell> : <Navigate to="/login"/> }
function App(){ const auth=useAuth(); return <BrowserRouter><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login auth={auth}/>}/><Route path="/register" element={<Login auth={auth} mode="register"/>}/><Route path="/dashboard" element={<Protected auth={auth}><Dashboard/></Protected>}/><Route path="/alerts" element={<Protected auth={auth}><Alerts/></Protected>}/><Route path="/alerts/:id" element={<Protected auth={auth}><AlertDetails/></Protected>}/><Route path="/incidents" element={<Protected auth={auth}><Incidents/></Protected>}/><Route path="/incidents/:id" element={<Protected auth={auth}><IncidentDetails/></Protected>}/><Route path="/threat-intel" element={<Protected auth={auth}><ThreatIntel/></Protected>}/><Route path="/mitre" element={<Protected auth={auth}><Mitre/></Protected>}/><Route path="/endpoints" element={<Protected auth={auth}><Endpoints/></Protected>}/><Route path="/reports" element={<Protected auth={auth}><Reports/></Protected>}/><Route path="/admin" element={<Protected auth={auth}><Admin/></Protected>}/><Route path="/settings" element={<Protected auth={auth}><SimplePage title="Settings" kicker="Platform preferences"/></Protected>}/><Route path="/profile" element={<Protected auth={auth}><SimplePage title="Profile" kicker="Operator identity"/></Protected>}/><Route path="*" element={<Navigate to="/dashboard"/>}/></Routes></BrowserRouter> }
createRoot(document.getElementById('root')).render(<App/>);
